
[font]
size = 14.0

[font.normal]
family = "Fira Code Nerd Font Mono"

[selection]
save_to_clipboard = true

[window]
opacity = 1.0

[general]
import = ["/home/shiroha/.config/alacritty/alacritty-theme/themes/nord.toml"]
