-- keybindings
vim.g.mapleader = ","
vim.keymap.set('n', '<Leader>t', '<CMD>ToggleTerm<CR>')
vim.keymap.set('t', '<Leader>t', '<CMD>ToggleTerm<CR>')
vim.keymap.set('n', 'j', 'gj')
vim.keymap.set('n', 'k', 'gk')
vim.keymap.set('n', '<TAB>', ':bn<CR>')
vim.keymap.set('n', '<S-TAB>', ':bp<CR>')
vim.keymap.set('n', '<Leader>v', ':vert split')
vim.keymap.set('n', '<Leader>V', ':topleft vert split')
vim.keymap.set('n', '<Leader>s', ':split')
vim.keymap.set('n', '<C-h>', '<C-w>h')
vim.keymap.set('n', '<C-j>', '<C-w>j')
vim.keymap.set('n', '<C-k>', '<C-w>k')
vim.keymap.set('n', '<C-l>', '<C-w>l')
vim.keymap.set('n', '<C-Up>', '<CMD>res +2<CR>')
vim.keymap.set('n', '<C-Down>', '<CMD>res -2<CR>')
vim.keymap.set('n', '<C-Left>', '<CMD>vert res +2<CR>')
vim.keymap.set('n', '<C-Right>', '<CMD>vert res -2<CR>')
vim.keymap.set('t', '<ESC>', '<C-\\><C-n>')
vim.keymap.set('n', '<Leader>rc', ':e $MYVIMRC')
vim.keymap.set('n', '<Leader>so', ':so $MYVIMRC')
vim.keymap.set('n', '<Leader>d',  '<CMD>NvimTreeToggle<CR>')
vim.keymap.set('n', '<Leader>q',  '<CMD>bd<CR>')
vim.keymap.set('i', '<S-Tab>', '<C-D>')

